---
# sample .automationthingy.yaml for your viewing pleasure
secretmgr:
  vault:
    token: "root"
    addr: "http://10.43.56.96:8200"

general:
  api:
    port: "8081"
    host: "http://localhost:8081/"
    auth:
      github:
        clientid: "5749cc64ea32a1506ea7"
        redirecturi: "http://localhost:8081/api/v1/login/github/callback"
        secrettype: "vault"
        secretref: "kv-v1/keys/githubapp"
  web:
    port: "8080"
    host: "http://localhost:8080/"
    auth:
      github:
        clientid: "5749cc64ea32a1506ea7"
        redirecturi: "http://localhost:8080/login/github/callback"
        secrettype: "vault"
        secretref: "kv-v1/keys/githubapp"
# define roles
rbac:
  roles:
    - name: "admin"
    - name: "developers"

  # define how groups (set via auth) map to roles
  grouprolemapping:
    - name: "admin"
      roles:
        - "admin"
    - name: "developers"
      roles:
        - "developers"

  # define how users map to roles
  userrolemapping:
    - name: "me@petermcconnell.com"
      roles:
        - "admin"

# declare some scripts 'inline'
scripts:
  - id: "268c55ac-6e2b-4c99-b84c-535b7d7e6cbd"
    name: "execute as a kubernetes job"
    desc: "this one we want to execute as a kubernetes job"
    kubernetesjob:
      namespace: "default"
      cluster: "default"
      ttlsecondsafterfinished: 100
      image: "python:3.8"
      imagepullpolicy: "Always"
      restartpolicy: "Never"
      backofflimit: 3
      parallelism: 1
      completions: 1
    categories:
      - "production ops / other category"
      - "more stuff"
    command:
      - "python3"
      - "main.py"
    rbac:
      - roles:
          - name: "developers"
            permissions:
              - "read"
              - "execute"
  - id: "868c55ac-6e2b-4c99-b84c-535b7d7e6cbc"
    name: "a script from disk"
    desc: "this is another little script which we're loading direct from disk"
    categories:
      - "production ops / other category"
      - "more stuff"
    workdir: "scripts/960fde7e-6f47-45e2-ab38-300b5ec84707/mythingy/"
    command:
      - "python3"
      - "main.py"
    rbac:
      - roles:
          - name: "developers"
            permissions:
              - "read"
              - "execute"

# pull in more scripts from external sources
sources:
  git:
    - repo: "git@github.com:peter-mcconnell/oneofmyautomationthingys.git"
      branch: "refs/heads/master"
      secrettype: "vault"
      secretref: "kv-v1/keys/key-automationthingy"
      rbac:
        - roles:
            - name: "developers"
              permissions:
                - "read"

# secret manager configurations
secretmgrs:
  vault:
    addr: "http://10.43.56.96:8200"
    tokenfilepath: ".vaulttoken"
